package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"net/http"
	"strconv"
	"strings"
	"sync"

	"github.com/gin-gonic/gin"
)

const baseUrl = "https://api.random.org/json-rpc/4/invoke"

type AutoGenerated struct {
	Jsonrpc string `json:"jsonrpc"`
	Result  struct {
		Random struct {
			Data           []int  `json:"data"`
			CompletionTime string `json:"completionTime"`
		} `json:"random"`
		BitsUsed      int `json:"bitsUsed"`
		BitsLeft      int `json:"bitsLeft"`
		RequestsLeft  int `json:"requestsLeft"`
		AdvisoryDelay int `json:"advisoryDelay"`
	} `json:"result"`
	ID int `json:"id"`
}

type result struct {
	Stddev int   `json:"stddev"`
	Data   []int `json:"data"`
}

// Function responsible for consuming Random.org API
func getRandomNumbersFromApi(n int, min int, max int) (data *AutoGenerated, err error) {

	requestBody := strings.NewReader(fmt.Sprintf(`{
		"jsonrpc": "2.0",
		"method": "generateIntegers",
		"params": {
			"apiKey": "63c31ebc-6c50-46b7-83bd-10001776c680",
			"n": %d,
			"min": %d,
			"max": %d,
			"replacement": true
		},
		"id": 42
	}`, n, min, max))

	response, err := http.Post(baseUrl, "application/json", requestBody)
	if err != nil {
		return nil, err
	}

	err = json.NewDecoder(response.Body).Decode(&data)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// Getting random numbers from API concurrently based on number of requests provided in GET query params
func getRandomNumbersConcurrently(numOfRequests int, n int, min int, max int) sync.Map {
	var randomNumbersMap sync.Map
	wg := sync.WaitGroup{}

	for i := 0; i < numOfRequests; i++ {
		wg.Add(1)
		go func(idx int) {
			data, err := getRandomNumbersFromApi(n, min, max)
			if err != nil {
				log.Fatal(err)
			}
			randomNumbersMap.Store(idx, data.Result.Random.Data)
			wg.Done()
		}(i)
	}
	wg.Wait()
	return randomNumbersMap
}

// Responsible for calculating standard deviation from slice of ints
func stddev(d []int) int {
	var num []float64
	var sum, mean, sd float64
	for i := 0; i < len(d); i++ {
		num = append(num, float64(d[i]))
		sum += num[i]
	}
	mean = sum / float64(len(num))

	for j := 0; j < len(num); j++ {
		sd += math.Pow(num[j]-mean, 2)
	}
	sd = math.Sqrt(sd / float64(len(num)))
	return int(sd)
}

// Function responsible for converting sync.Map into a standard Map
func convertSyncMap(m sync.Map) []result {
	var results []result
	var r result
	m.Range(func(key, value interface{}) bool {

		// Calculating standard deviation
		r.Stddev = stddev(value.([]int))
		r.Data = value.([]int)
		results = append(results, r)
		return true
	})

	r.Data = []int{}
	for i := 0; i < len(results[0].Data); i++ {
		for j := 0; j < len(results); j++ {
			r.Data = append(r.Data, results[j].Data[i])
		}
	}
	r.Stddev = stddev(r.Data)
	results = append(results, r)

	return results
}

func getMethod(c *gin.Context) {

	requests, err := strconv.Atoi(c.DefaultQuery("requests", "1"))
	if err != nil {
		log.Fatal(err)
	}

	length, err := strconv.Atoi(c.Query("length"))
	if err != nil {
		log.Fatal(err)
	}
	randomNumbersMap := getRandomNumbersConcurrently(requests, length, 1, 10)

	c.IndentedJSON(http.StatusOK, convertSyncMap(randomNumbersMap))
}

func main() {
	router := gin.Default()
	router.GET("/random/mean", getMethod)
	router.Run(":8000")
}
